name: Deploy to Tencent Cloud

on:
  push:
    branches:
      - feature

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect and deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd portfolio-cg
            git pull origin feature
            docker rmi nextjs-dev-app || true
            docker build -t nextjs-dev-app .
            docker stop nextjs-dev-app || true && docker rm nextjs-dev-app || true
            docker run -d --name nextjs-dev-app -p 3002:3002 nextjs-dev-app
